name: pomo
description: Cross-platform Pomodoro timer with hourly time tracking, Notion PARA sync, and RGB webhooks
version: 1.3.9+1
publish_to: none

environment:
  sdk: "^3.6.0"

dependencies:
  audioplayers: ^6.0.0
  bloc: ^8.1.3
  desktop_multi_window: ^0.2.1
  dio: ^5.4.3+1
  equatable: ^2.0.5
  file_picker: ^8.1.3
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_bloc: ^8.1.6
  flutter_local_notifications: ^18.0.1
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  intl: ^0.20.2
  launch_at_startup: ^0.3.1
  logger: ^2.2.0
  package_info_plus: ^8.1.0
  path_provider: ^2.1.5
  permission_handler: ^11.3.1
  shared_preferences: ^2.2.3
  url_launcher: ^6.3.1
  window_manager: ^0.4.3

dev_dependencies:
  bloc_test: ^9.1.6
  flutter_launcher_icons: ^0.14.2
  flutter_native_splash: ^2.4.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  very_good_analysis: ^7.0.0

flutter:
  uses-material-design: true
  generate: true

  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
        - asset: fonts/Roboto-Medium.ttf
          weight: 500
        - asset: fonts/Roboto-Bold.ttf
          weight: 700

    - family: Rubik Mono One
      fonts:
        - asset: fonts/RubikMonoOne-Regular.ttf

    - family: Lilita One
      fonts:
        - asset: fonts/LilitaOne-Regular.ttf

    - family: Major Mono Display
      fonts:
        - asset: fonts/MajorMonoDisplay-Regular.ttf

  assets:
    - 'assets/sounds/click.aac'
    - 'assets/sounds/pop.aac'
    - 'assets/sounds/ding_dong.aac'
    - 'assets/sounds/chime.wav'
    - 'assets/sounds/bell.wav'
    - 'assets/sounds/digital_beep.wav'
    - 'assets/images/pomo_logo.svg'
    - 'assets/images/pomo_logo.png'
    - 'assets/images/pomo_splash.png'
    - 'assets/images/pomo_splash_64.png'
    - 'assets/images/notion_logo.svg'
    - 'fonts/MajorMonoDisplay-Regular.ttf'
    - 'fonts/RubikMonoOne-Regular.ttf'
    - 'fonts/LilitaOne-Regular.ttf'
    - 'fonts/Roboto-Regular.ttf'
    - 'fonts/Roboto-Medium.ttf'
    - 'fonts/Roboto-Bold.ttf'
